pool:
    vmImage: windows-2022

variables:
- group: android_keystore_var
- name: buildConfiguration
  value: 'Release'
- name: outputDirectory
  value: '$(Build.SourcesDirectory)/TrojanPlusApp.Android/bin/$(buildConfiguration)/net10.0-android'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dotnet workload install maui-android --skip-sign-check'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*Android*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'TrojanPlusApp.Android/TrojanPlusApp.Android.csproj'
    arguments: '--configuration $(buildConfiguration) --framework net10.0-android'

- task: AndroidSigning@3
  inputs:
    apkFiles: '$(outputDirectory)/com.trojan_plus.android.apk'
    apksign: true
    apksignerKeystoreFile: 'trojan_plush_android_key.jks'
    apksignerKeystorePassword: $(keystore-password)
    apksignerKeystoreAlias: $(key-alias)
    apksignerKeyPassword: $(key-password)
    apksignerArguments: --out $(outputDirectory)/com.trojan_plus.android.release.apk
    zipalign: true
      
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDirectory)/com.trojan_plus.android.release.apk'
    ArtifactName: 'AndroidAPK'
    publishLocation: 'Container'