pool:
    vmImage: windows-2022

variables:
- group: android_keystore_var
- name: buildConfiguration
  value: 'Release'
- name: outputDirectory
  value: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'workload'
    arguments: 'install maui-android'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*Android*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(outputDirectory) --framework net10.0-android'

- task: AndroidSigning@3
  inputs: 
    apkFiles: '$(outputDirectory)/*.apk'
    apksign: true
    apksignerKeystoreFile: 'trojan_plush_android_key.jks'
    apksignerKeystorePassword: $(keystore-password)
    apksignerKeystoreAlias: $(key-alias)
    apksignerKeyPassword: $(key-password)
    apksignerArguments: --out $(outputDirectory)/com.trojan_plus.android.release.apk
    zipalign: true
      
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDirectory)/com.trojan_plus.android.release.apk'
    ArtifactName: 'AndroidAPK'
    publishLocation: 'Container'