//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrojanPlusApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrojanPlusApp.Resx.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string Common_AlertTitle {
            get {
                return ResourceManager.GetString("Common_AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Common_AskTitle {
            get {
                return ResourceManager.GetString("Common_AskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Common_ErrorTitle {
            get {
                return ResourceManager.GetString("Common_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Hosts_ToolbarAdd {
            get {
                return ResourceManager.GetString("Hosts_ToolbarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Hosts.
        /// </summary>
        public static string HostsView_Title {
            get {
                return ResourceManager.GetString("HostsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vpn.example.com.
        /// </summary>
        public static string New_HostAddressHolder {
            get {
                return ResourceManager.GetString("New_HostAddressHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Address:.
        /// </summary>
        public static string New_HostAddressTitle {
            get {
                return ResourceManager.GetString("New_HostAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t want to delete this host?.
        /// </summary>
        public static string New_HostDeleteAskText {
            get {
                return ResourceManager.GetString("New_HostDeleteAskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete This Host.
        /// </summary>
        public static string New_HostDeleteText {
            get {
                return ResourceManager.GetString("New_HostDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Pipeline Mode.
        /// </summary>
        public static string New_HostEnablePipeline {
            get {
                return ResourceManager.GetString("New_HostEnablePipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION: Please confirm server&apos;s pipeline mode has been enabled, otherwise you won&apos;t connect host successfully..
        /// </summary>
        public static string New_HostEnablePipelineDetail {
            get {
                return ResourceManager.GetString("New_HostEnablePipelineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the host of name.
        /// </summary>
        public static string New_HostErrorNeedName {
            get {
                return ResourceManager.GetString("New_HostErrorNeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Options:.
        /// </summary>
        public static string New_HostExperimentalTitle {
            get {
                return ResourceManager.GetString("New_HostExperimentalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Host named [{0}] has been added, please rename your new host..
        /// </summary>
        public static string New_HostHasBeenAdded {
            get {
                return ResourceManager.GetString("New_HostHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input A Identified Name for Your Host.
        /// </summary>
        public static string New_HostNameHolder {
            get {
                return ResourceManager.GetString("New_HostNameHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name:.
        /// </summary>
        public static string New_HostNameTitle {
            get {
                return ResourceManager.GetString("New_HostNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Password for vlidation.
        /// </summary>
        public static string New_HostPasswordHolder {
            get {
                return ResourceManager.GetString("New_HostPasswordHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password of Host:.
        /// </summary>
        public static string New_HostPasswordTitle {
            get {
                return ResourceManager.GetString("New_HostPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-65535.
        /// </summary>
        public static string New_HostPortHolder {
            get {
                return ResourceManager.GetString("New_HostPortHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Opening Port:.
        /// </summary>
        public static string New_HostPortTitle {
            get {
                return ResourceManager.GetString("New_HostPortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Host Domain.
        /// </summary>
        public static string New_HostSSLVerify {
            get {
                return ResourceManager.GetString("New_HostSSLVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION: Whether verify certification of host domain, please DO check this option if you want to go through the real GFW and fill host address as a domain instead of IP. .
        /// </summary>
        public static string New_HostSSLVerifyDetail {
            get {
                return ResourceManager.GetString("New_HostSSLVerifyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string New_ToolbarCancel {
            get {
                return ResourceManager.GetString("New_ToolbarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string New_ToolbarSave {
            get {
                return ResourceManager.GetString("New_ToolbarSave", resourceCulture);
            }
        }
    }
}
