//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrojanPlusApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrojanPlusApp.Resx.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##
        ///## Bundle of CA Root Certificates
        ///##
        ///## Certificate data from Mozilla as of: Wed Jan  1 04:12:10 2020 GMT
        ///##
        ///## This is a bundle of X.509 certificates of public Certificate Authorities
        ///## (CA). These were automatically extracted from Mozilla&apos;s root certificates
        ///## file (certdata.txt).  This file can be found in the mozilla source tree:
        ///## https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt
        ///##
        ///## It contains the certificates in PEM format  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cacert {
            get {
                return ResourceManager.GetString("cacert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.1.0/24
        ///1.0.2.0/23
        ///1.0.8.0/21
        ///1.0.32.0/19
        ///1.1.0.0/24
        ///1.1.2.0/23
        ///1.1.4.0/22
        ///1.1.8.0/21
        ///1.1.16.0/20
        ///1.1.32.0/19
        ///1.2.0.0/23
        ///1.2.2.0/24
        ///1.2.4.0/22
        ///1.2.8.0/21
        ///1.2.16.0/20
        ///1.2.32.0/19
        ///1.2.64.0/18
        ///1.3.0.0/16
        ///1.4.1.0/24
        ///1.4.2.0/23
        ///1.4.4.0/22
        ///1.4.8.0/21
        ///1.4.16.0/20
        ///1.4.32.0/19
        ///1.4.64.0/18
        ///1.8.0.0/16
        ///1.10.0.0/21
        ///1.10.8.0/23
        ///1.10.11.0/24
        ///1.10.12.0/22
        ///1.10.16.0/20
        ///1.10.32.0/19
        ///1.10.64.0/18
        ///1.12.0.0/14
        ///1.18.128.0/24
        ///1.24.0.0/13
        ///1.45.0.0/16
        ///1.48.0.0/14
        ///1.56.0.0/13
        ///1.68.0.0/14
        ///1. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cn_mainland_ips {
            get {
                return ResourceManager.GetString("cn_mainland_ips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        public static string Common_AlertTitle {
            get {
                return ResourceManager.GetString("Common_AlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Common_AskTitle {
            get {
                return ResourceManager.GetString("Common_AskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Common_ErrorTitle {
            get {
                return ResourceManager.GetString("Common_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 030buy.com
        ///0rz.tw
        ///1000giri.net
        ///100ke.org
        ///10conditionsoflove.com
        ///10musume.com
        ///10.tt
        ///123rf.com
        ///12bet.com
        ///12vpn.com
        ///12vpn.net
        ///138.com
        ///141hongkong.com
        ///141jj.com
        ///141tube.com
        ///1688.com.au
        ///173ng.com
        ///177pic.info
        ///17t17p.com
        ///18board.com
        ///18board.info
        ///18onlygirls.com
        ///18p2p.com
        ///18virginsex.com
        ///1949er.org
        ///1984bbs.com
        ///1984bbs.org
        ///1989report.hkja.org.hk
        ///1991way.com
        ///1998cdp.org
        ///1-apple.com.tw
        ///1bao.org
        ///1dumb.com
        ///1e100.net
        ///1eew.com
        ///1mobile.com
        ///1mobile.tw
        ///1pondo.tv
        ///2000fun.com
        ///2008xianzhan [rest of string was truncated]&quot;;.
        /// </summary>
        public static string gfwlist {
            get {
                return ResourceManager.GetString("gfwlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Hosts_BtnConnect {
            get {
                return ResourceManager.GetString("Hosts_BtnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Hosts_BtnDisconnect {
            get {
                return ResourceManager.GetString("Hosts_BtnDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Host has a load balance host without enabling pipeline mode. Please check..
        /// </summary>
        public static string Hosts_LoadBalanceNodeError {
            get {
                return ResourceManager.GetString("Hosts_LoadBalanceNodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a host..
        /// </summary>
        public static string Hosts_PleaseAddHost {
            get {
                return ResourceManager.GetString("Hosts_PleaseAddHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_AboutTitle {
            get {
                return ResourceManager.GetString("Menu_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Menu_HostsToolbarAdd {
            get {
                return ResourceManager.GetString("Menu_HostsToolbarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Hosts.
        /// </summary>
        public static string Menu_HostsViewTitle {
            get {
                return ResourceManager.GetString("Menu_HostsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_SettingsTitle {
            get {
                return ResourceManager.GetString("Menu_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Host.
        /// </summary>
        public static string New_AddHostTitle {
            get {
                return ResourceManager.GetString("New_AddHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a name for new host:.
        /// </summary>
        public static string New_AskDuplicatePrompt {
            get {
                return ResourceManager.GetString("New_AskDuplicatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFWList Up Stream DNS Server.
        /// </summary>
        public static string New_DNS_GFW_UpStreamNS {
            get {
                return ResourceManager.GetString("New_DNS_GFW_UpStreamNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Mainland Up Stream DNS Server.
        /// </summary>
        public static string New_DNS_UpStreamNS {
            get {
                return ResourceManager.GetString("New_DNS_UpStreamNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Host.
        /// </summary>
        public static string New_EditHostTitle {
            get {
                return ResourceManager.GetString("New_EditHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable TCP Fast Open.
        /// </summary>
        public static string New_EnableFastOpen {
            get {
                return ResourceManager.GetString("New_EnableFastOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION: Might need Root to enable. After enabling, it can reduce some delay, but might decrease bandwidth seriously, please test bandwith after enabling..
        /// </summary>
        public static string New_EnableFastOpenDetail {
            get {
                return ResourceManager.GetString("New_EnableFastOpenDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Some information are wrong, please check those elements empty or marked as red..
        /// </summary>
        public static string New_ErrorAttributes {
            get {
                return ResourceManager.GetString("New_ErrorAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vpn.example.com.
        /// </summary>
        public static string New_HostAddressHolder {
            get {
                return ResourceManager.GetString("New_HostAddressHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Address:.
        /// </summary>
        public static string New_HostAddressTitle {
            get {
                return ResourceManager.GetString("New_HostAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t want to delete this host?.
        /// </summary>
        public static string New_HostDeleteAskText {
            get {
                return ResourceManager.GetString("New_HostDeleteAskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete This Host.
        /// </summary>
        public static string New_HostDeleteText {
            get {
                return ResourceManager.GetString("New_HostDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate This Host.
        /// </summary>
        public static string New_HostDuplicateText {
            get {
                return ResourceManager.GetString("New_HostDuplicateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Pipeline Mode.
        /// </summary>
        public static string New_HostEnablePipeline {
            get {
                return ResourceManager.GetString("New_HostEnablePipeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION: Please confirm server&apos;s pipeline mode has been enabled, otherwise you won&apos;t connect host successfully..
        /// </summary>
        public static string New_HostEnablePipelineDetail {
            get {
                return ResourceManager.GetString("New_HostEnablePipelineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the host of name.
        /// </summary>
        public static string New_HostErrorNeedName {
            get {
                return ResourceManager.GetString("New_HostErrorNeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental Options:.
        /// </summary>
        public static string New_HostExperimentalTitle {
            get {
                return ResourceManager.GetString("New_HostExperimentalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Host named [{0}] has been added, please rename your new host..
        /// </summary>
        public static string New_HostHasBeenAdded {
            get {
                return ResourceManager.GetString("New_HostHasBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input A Identified Name for Your Host.
        /// </summary>
        public static string New_HostNameHolder {
            get {
                return ResourceManager.GetString("New_HostNameHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name:.
        /// </summary>
        public static string New_HostNameTitle {
            get {
                return ResourceManager.GetString("New_HostNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Password for vlidation.
        /// </summary>
        public static string New_HostPasswordHolder {
            get {
                return ResourceManager.GetString("New_HostPasswordHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password of Host:.
        /// </summary>
        public static string New_HostPasswordTitle {
            get {
                return ResourceManager.GetString("New_HostPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-65535.
        /// </summary>
        public static string New_HostPortHolder {
            get {
                return ResourceManager.GetString("New_HostPortHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Opening Port:.
        /// </summary>
        public static string New_HostPortTitle {
            get {
                return ResourceManager.GetString("New_HostPortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Host Domain.
        /// </summary>
        public static string New_HostSSLVerify {
            get {
                return ResourceManager.GetString("New_HostSSLVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION: Whether verify certification of host domain, please DO check this option if you want to go through the real GFW and fill host address as a domain instead of IP. .
        /// </summary>
        public static string New_HostSSLVerifyDetail {
            get {
                return ResourceManager.GetString("New_HostSSLVerifyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete &apos;{0}&apos; loadbalance node?.
        /// </summary>
        public static string New_LoadBalanceDelHostAsk {
            get {
                return ResourceManager.GetString("New_LoadBalanceDelHostAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Balance Hosts.
        /// </summary>
        public static string New_LoadBalanceHost {
            get {
                return ResourceManager.GetString("New_LoadBalanceHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add others host with pipeline mode as a loadbalance node to proxy together to increase bandwith. Caution: please make sure the ping among all server hosts is low than 10ms, otherwise you will get terriable proxy experience..
        /// </summary>
        public static string New_LoadBalanceHost_Detail {
            get {
                return ResourceManager.GetString("New_LoadBalanceHost_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add another host with pipeline mode firstly..
        /// </summary>
        public static string New_LoadBalanceHost_Error {
            get {
                return ResourceManager.GetString("New_LoadBalanceHost_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No any LoadBalance node&gt;.
        /// </summary>
        public static string New_LoadBalanceHost_NoHosts {
            get {
                return ResourceManager.GetString("New_LoadBalanceHost_NoHosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a host:.
        /// </summary>
        public static string New_LoadBalanceHost_Title {
            get {
                return ResourceManager.GetString("New_LoadBalanceHost_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Debug Log.
        /// </summary>
        public static string New_Output_Debug_Log {
            get {
                return ResourceManager.GetString("New_Output_Debug_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION: only for developer, if you enable, proxy performance will be reduced a lot..
        /// </summary>
        public static string New_Output_Debug_Log_Detail {
            get {
                return ResourceManager.GetString("New_Output_Debug_Log_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Type:.
        /// </summary>
        public static string New_RouteType {
            get {
                return ResourceManager.GetString("New_RouteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy All.
        /// </summary>
        public static string New_RouteType_All {
            get {
                return ResourceManager.GetString("New_RouteType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass China Mainland.
        /// </summary>
        public static string New_RouteType_Bypass_CN {
            get {
                return ResourceManager.GetString("New_RouteType_Bypass_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass China Mainland and Local.
        /// </summary>
        public static string New_RouteType_Bypass_CN_Local {
            get {
                return ResourceManager.GetString("New_RouteType_Bypass_CN_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass Local.
        /// </summary>
        public static string New_RouteType_Bypass_Local {
            get {
                return ResourceManager.GetString("New_RouteType_Bypass_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy China Mainland.
        /// </summary>
        public static string New_RouteType_CN {
            get {
                return ResourceManager.GetString("New_RouteType_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy GFWList.
        /// </summary>
        public static string New_RouteType_GFWList {
            get {
                return ResourceManager.GetString("New_RouteType_GFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string New_ToolbarCancel {
            get {
                return ResourceManager.GetString("New_ToolbarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string New_ToolbarSave {
            get {
                return ResourceManager.GetString("New_ToolbarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trojan Plus auto start and stop VPN notification, you can change this in Trojan Plus App&apos;s Settings page..
        /// </summary>
        public static string Notification_AutoChannelDescription {
            get {
                return ResourceManager.GetString("Notification_AutoChannelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trojan Plus Auto Start/Stop Notification.
        /// </summary>
        public static string Notification_AutoChannelName {
            get {
                return ResourceManager.GetString("Notification_AutoChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trojan Plus VPN Auto Started in Cellur.
        /// </summary>
        public static string Notification_AutoStart {
            get {
                return ResourceManager.GetString("Notification_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trojan Plus VPN Auto Stopped in Wifi.
        /// </summary>
        public static string Notification_AutoStop {
            get {
                return ResourceManager.GetString("Notification_AutoStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trojan Plus can help you bypass GFW..
        /// </summary>
        public static string Notification_ChannelDescription {
            get {
                return ResourceManager.GetString("Notification_ChannelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trojan Plus Notification.
        /// </summary>
        public static string Notification_ChannelName {
            get {
                return ResourceManager.GetString("Notification_ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trojan Plus Service is runing as VPN.
        /// </summary>
        public static string Notification_Title {
            get {
                return ResourceManager.GetString("Notification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Function Note.
        /// </summary>
        public static string Settings_AutoFunctionNote {
            get {
                return ResourceManager.GetString("Settings_AutoFunctionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As we test, in order to saving battery, latest Android&apos;s system (Android 9/10) will limit backgroud tasks auto-start by themself so that these 2 auto function do not response as soon as condition fullfilled, they all have a uncertain delay time..
        /// </summary>
        public static string Settings_AutoFunctionNoteDetail {
            get {
                return ResourceManager.GetString("Settings_AutoFunctionNoteDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start in Cellur Network.
        /// </summary>
        public static string Settings_AutoStartCellur {
            get {
                return ResourceManager.GetString("Settings_AutoStartCellur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start VPN service in cellur network by former starting host config..
        /// </summary>
        public static string Settings_AutoStartCellurDetail {
            get {
                return ResourceManager.GetString("Settings_AutoStartCellurDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Stop in Wifi Network.
        /// </summary>
        public static string Settings_AutoStopWifi {
            get {
                return ResourceManager.GetString("Settings_AutoStopWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add a Wifi SSID.
        /// </summary>
        public static string Settings_AutoStopWifiAdd {
            get {
                return ResourceManager.GetString("Settings_AutoStopWifiAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this wifi SSID which can auto stop VPN?.
        /// </summary>
        public static string Settings_AutoStopWifiDelete {
            get {
                return ResourceManager.GetString("Settings_AutoStopWifiDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto stop VPN service when added Wifi SSID connected. This option was used for those Wifi enviroment have been configured for transparent proxy. It just work when Trojan Plus is Background.
        ///CAUTION: because privacy information controlling is much more strict in Android 10+, we cannot get SSID, if you add any wifi SSID, VPN will auto close in any Wifi..
        /// </summary>
        public static string Settings_AutoStopWifiDetail {
            get {
                return ResourceManager.GetString("Settings_AutoStopWifiDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notification.
        /// </summary>
        public static string Settings_EnableAndroidNotification {
            get {
                return ResourceManager.GetString("Settings_EnableAndroidNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a notification in status bar to indicate VPN service is running..
        /// </summary>
        public static string Settings_EnableAndroidNotificationDetail {
            get {
                return ResourceManager.GetString("Settings_EnableAndroidNotificationDetail", resourceCulture);
            }
        }
    }
}
